#!/usr/bin/env python3
# __author__ = 'David Choi (bestshoot21@gmail.com)'
"""Agent stop hook: commit and push safe repo changes after an agent turn.

Purpose
-------
Runs on a ``Stop`` hook event. Before committing, the repository test suite
must pass. Only known source/documentation paths are staged; secrets, local
runtime files, and binary assets are always ignored. The commit message uses
the Conventional Commits rules documented in ``AGENTS.md``.

Fails open: hook errors never block the agent from finishing.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

SKIP_PATH_RE = re.compile(
    r"(^|/)(\.env($|\.)|.*\.pem$|.*credentials.*|.*secret.*|auth\.json$|\.cursor/debug.*\.log$|.*\.(png|jpe?g|gif|webp|sqlite3?|db|bin|safetensors)$)",
    re.IGNORECASE,
)
CURSOR_BRANDING_RE = re.compile(
    r"\b(created by cursor|co-?authored-?by:.*cursor|generated by cursor)\b",
    re.IGNORECASE,
)

SCOPE_MAP = {
    "scripts": "scripts",
    "skills": "skills",
    "tests": "tests",
    "docs": "docs",
    "config": "config",
    "cron": "cron",
    "bootstrap": "bootstrap",
    "browser": "browser",
    ".cursor": "hooks",
    "local-model": "local-model",
    "mcp": "mcp",
}

ALLOWED_TOP_LEVELS = {
    ".codex",
    ".cursor",
    "bootstrap",
    "browser",
    "config",
    "cron",
    "docs",
    "local-model",
    "mcp",
    "scripts",
    "skills",
    "tests",
}
ALLOWED_ROOT_FILES = {"AGENTS.md", "README.md"}

# (path substring match, summary phrase) — first matching entries are combined.
THEME_SUMMARIES: tuple[tuple[str, str], ...] = (
    ("cron_health", "harden scheduler"),
    ("cron/", "harden cron scheduler"),
    ("max_parallel", "limit cron parallelism"),
    ("auto_git_commit", "add auto-commit hook"),
    ("hooks.json", "add auto-commit hook"),
    ("interview_trends", "add live interview trend ingestion"),
    ("papers_digest", "improve papers digest"),
    ("english_intake", "improve english lesson intake"),
    ("english_srs", "improve english SRS deck"),
    ("agenda.py", "improve calendar agenda helper"),
    ("dev-history", "record dev history"),
    ("project-overview", "sync project overview"),
)


def _run(cmd: list[str], *, cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)


def _git_root(start: Path) -> Path | None:
    result = _run(["git", "rev-parse", "--show-toplevel"], cwd=start)
    if result.returncode != 0:
        return None
    return Path(result.stdout.strip())


def _list_changed(repo: Path) -> list[str]:
    result = _run(["git", "status", "--porcelain"], cwd=repo)
    if result.returncode != 0:
        return []
    paths: list[str] = []
    for line in result.stdout.splitlines():
        if len(line) < 4:
            continue
        path = line[3:].strip()
        if " -> " in path:
            path = path.split(" -> ", 1)[1].strip()
        paths.append(path)
    return paths


def _should_skip(path: str) -> bool:
    normalized = path[2:] if path.startswith("./") else path
    top_level = normalized.split("/", 1)[0]
    allowed = top_level in ALLOWED_TOP_LEVELS or normalized in ALLOWED_ROOT_FILES
    return not allowed or bool(SKIP_PATH_RE.search(normalized))


def _productive_paths(paths: list[str]) -> list[str]:
    """Paths that should drive type/scope, excluding test-only noise."""
    return [p for p in paths if not p.startswith("tests/")]


def _commit_type(paths: list[str]) -> str:
    productive = _productive_paths(paths)
    targets = productive or paths

    if all(p.startswith("tests/") for p in paths):
        return "test"
    if all(p.startswith("docs/") for p in targets):
        return "docs"
    if any(p.startswith(".cursor/") for p in targets):
        return "chore"
    if any(p.startswith("config/") for p in targets):
        return "chore"
    if any(p.startswith(("scripts/", "skills/", "cron/", "bootstrap/")) for p in targets):
        return "feat"
    return "chore"


def _commit_scope(paths: list[str]) -> str | None:
    productive = _productive_paths(paths)
    targets = productive or paths
    joined = " ".join(targets).lower()

    if "cron" in joined:
        return "cron"
    if any(p.startswith(".cursor/") for p in targets):
        return "hooks"

    scopes: list[str] = []
    for path in targets:
        top = path.split("/", 1)[0]
        scope = SCOPE_MAP.get(top)
        if scope and scope != "tests":
            scopes.append(scope)
    if not scopes:
        return None
    return Counter(scopes).most_common(1)[0][0]


def _theme_summary(paths: list[str]) -> str | None:
    joined = " ".join(paths).lower()
    phrases: list[str] = []
    seen: set[str] = set()
    for needle, phrase in THEME_SUMMARIES:
        if needle in joined and phrase not in seen:
            phrases.append(phrase)
            seen.add(phrase)
    if not phrases:
        return None
    return " and ".join(phrases)


def _basename_summary(paths: list[str]) -> str:
    basenames = sorted({Path(p).name for p in paths})
    if len(basenames) == 1:
        stem = Path(basenames[0]).stem.replace("_", " ")
        return f"update {stem}"
    if len(paths) <= 3:
        return "update " + ", ".join(Path(p).name for p in sorted(paths))
    return f"update {len(paths)} files"


def _summarize(paths: list[str]) -> str:
    return _theme_summary(paths) or _basename_summary(paths)


def build_commit_message(paths: list[str]) -> str:
    """Build a Conventional Commits message without Cursor branding."""
    top_levels = {path.split("/", 1)[0] for path in paths}
    if len(paths) >= 10 and len(top_levels) >= 4:
        return "feat(agent): sync runtime integrations and automation"

    commit_type = _commit_type(paths)
    scope = _commit_scope(paths)
    summary = _summarize(paths)
    if scope:
        header = f"{commit_type}({scope}): {summary}"
    else:
        header = f"{commit_type}: {summary}"
    if CURSOR_BRANDING_RE.search(header):
        header = re.sub(CURSOR_BRANDING_RE, "", header).strip()
    return header


def _push_if_needed(repo: Path) -> tuple[bool, str]:
    """Push local commits when the current branch has a configured upstream."""
    upstream = _run(
        ["git", "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}"],
        cwd=repo,
    )
    if upstream.returncode != 0:
        return True, "no upstream; skipped push"

    ahead = _run(["git", "rev-list", "--count", "@{u}..HEAD"], cwd=repo)
    if ahead.returncode != 0:
        detail = (ahead.stderr or ahead.stdout or "").strip()
        return False, detail or "could not determine unpushed commit count"
    try:
        ahead_count = int(ahead.stdout.strip())
    except ValueError:
        return False, "invalid unpushed commit count"
    if ahead_count == 0:
        return True, "upstream already current"

    push = _run(["git", "push"], cwd=repo)
    if push.returncode != 0:
        detail = (push.stderr or push.stdout or "").strip()
        return False, f"push failed: {detail}"
    return True, f"pushed {ahead_count} commit(s)"


def commit_and_push(repo: Path) -> tuple[bool, str]:
    changed = _list_changed(repo)
    commit_paths = [p for p in changed if not _should_skip(p)]
    if not commit_paths:
        ok, detail = _push_if_needed(repo)
        return ok, f"no commit-worthy changes; {detail}"

    tests = _run([sys.executable, "-m", "pytest", "-q"], cwd=repo)
    if tests.returncode != 0:
        detail = (tests.stderr or tests.stdout or "pytest failed").strip()
        return False, f"tests failed; skipped commit: {detail}"

    add = _run(["git", "add", "--"] + commit_paths, cwd=repo)
    if add.returncode != 0:
        detail = (add.stderr or add.stdout or "").strip()
        return False, detail or "git add failed"

    staged = _run(["git", "diff", "--cached", "--name-only"], cwd=repo)
    if staged.returncode != 0 or not staged.stdout.strip():
        return True, "nothing staged after filtering"

    staged_paths = [
        path for path in staged.stdout.strip().splitlines() if not _should_skip(path)
    ]
    if not staged_paths:
        return True, "nothing staged after filtering"

    message = build_commit_message(staged_paths)
    # --only prevents unrelated files already present in the user's index from
    # being pulled into the automatic commit.
    commit = _run(["git", "commit", "--only", "-m", message, "--"] + staged_paths, cwd=repo)
    if commit.returncode != 0:
        detail = (commit.stderr or commit.stdout or "").strip()
        return False, detail or "git commit failed"

    ok, push_detail = _push_if_needed(repo)
    if not ok:
        return False, f"committed locally: {message}; {push_detail}"
    return True, f"committed: {message}; {push_detail}"


def _record_result(repo: Path, ok: bool, detail: str) -> None:
    """Write a local diagnostic without creating another commit-worthy file."""
    timestamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    outcome = "ok" if ok else "error"
    message = f"[{timestamp}] {outcome}: {detail.strip()[:4000]}"
    print(message, file=sys.stdout if ok else sys.stderr)
    try:
        with (repo / ".git" / "codex-auto-commit.log").open(
            "a", encoding="utf-8"
        ) as handle:
            handle.write(message + "\n")
    except OSError:
        pass


def main() -> int:
    try:
        json.load(sys.stdin)
    except json.JSONDecodeError:
        pass

    repo = _git_root(REPO_ROOT)
    if repo is None:
        return 0

    try:
        ok, detail = commit_and_push(repo)
    except Exception as exc:  # fail open, but make unexpected failures observable
        ok, detail = False, f"unexpected hook failure: {type(exc).__name__}: {exc}"
    _record_result(repo, ok, detail)
    return 0 if ok else 0  # fail open for stop hook


if __name__ == "__main__":
    raise SystemExit(main())
